"""
Django settings for fiados project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

import os 
from datetime import timedelta

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-k#-$+9gsvz#0%o3w0f7n!g&p1-ddza2u72fw&#-8t$=s!vm-a0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api.apps.ApiConfig',
    'rest_framework',
    'rest_framework_simplejwt', 
    'rest_framework.authtoken',
    'drf_spectacular', #django spectacular sirve como documentacion de swagger
    'corsheaders',
    'pwa'

]


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Debe ir antes de cualquier middleware que maneje solicitudes
    #'fiados.middleware.BlockPostmanMiddleware', #Ojo estos middleware se tienen que descomentar para produccion 
    #'fiados.middleware.CustomHeaderMiddleware', #Ojo estos middleware se tienen que descomentar para produccion
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', 
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware', 
]

ROOT_URLCONF = 'fiados.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  # Asegúrate de que esta línea esté presente
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'fiados.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

#Base de datos en desarrollo
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True
#Codigo para definir el formato de numeros. Ejemplo 100.000,00 (formato europeo/latinoamericano) o 100,000.00 (formato anglosajón),
USE_L10N = True  # Asegúrate que esté en True
USE_THOUSAND_SEPARATOR = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/



STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # Define la ruta para STATIC_ROOT
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

####Mi Codigo

#Aqui indico y permito que URL pueda accedar a la api
CORS_ALLOW_ALL_ORIGINS = False 
CORS_ALLOWED_ORIGINS = [
    "https://fiador.vercel.app",  # Web Produccion
    "https://localhost",          # App movil
    "http://localhost:8100",      # Solo se puede usar en desarrollo, para produccion se comenta
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'X-Api-Secret'  # Header personalizado
]

CORS_ALLOW_CREDENTIALS = True
CORS_EXPOSE_HEADERS = ['Content-Type', 'X-CSRFToken']

# Validacion para que solo los urls del CORS consuman la api en produccion
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"

SECURE_API_HEADER = 'X-Api-Secret'  
SECURE_API_VALUE = 'eb174615d2782bb216ae760d9df22bd559c17d97c4891a93907ea0f25ea535c5'  # DEBE SER EL MISMO QUE EN ANGULAR

AUTH_USER_MODEL = 'api.User'

REST_FRAMEWORK = {

    #DRF JWT
       'DEFAULT_AUTHENTICATION_CLASSES': (
           'rest_framework_simplejwt.authentication.JWTAuthentication',
       ),

    #PERMISOS
       'DEFAULT_PERMISSION_CLASS': ('rest_framework.permissions.IsAuthenticated',),
    #DRF SPECTACULAR
       'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
  
   }

SIMPLE_JWT = {
    'ALGORITHM': 'HS256',
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'JTI_CLAIM': 'jti',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',
    #Tiempo de expiracion del TOKEN

    #PARA DESARROLLO ESTA CONFIGURACION

    # Tiempo de vida del token de acceso (default: 5 minutos)
    #'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),  # 1 hora
    ## Tiempo de vida del token de refresco (default: 1 día)
    #'REFRESH_TOKEN_LIFETIME': timedelta(days=1),  # 1 semana

    #PARA PRODUCCION ESTA CONFIGURACION
    #'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'ACCESS_TOKEN_LIFETIME': timedelta(days=365*100),  # 100 años (prácticamente nunca)

    #'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=365*100),  # 100 años (prácticamente nunca)
    # Tiempo de vida del token de refresco cuando se usa para renovar (default: None)
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,

    # Permite renovar el refresh token cada vez que se usa
    'ROTATE_REFRESH_TOKENS': True,
    
    # Invalida los refresh tokens después de usarlos
    'BLACKLIST_AFTER_ROTATION': True,
    
    # Actualiza la última hora de inicio de sesión del usuario
    'UPDATE_LAST_LOGIN': True,
}
#Configuracion de Swagger
SPECTACULAR_SETTINGS = {
    'TITLE': 'Fiador API',
    'DESCRIPTION': 'API REST utilizada como Backend para la plataforma Fiador, el cual permite llevar el control de Fiados de los Clientes.',
    'VERSION': '1.0.0',
    'CONTACT': {
        'name': 'Fiador',
        'email': 'jesusmedina0921@gmail.com',
        'url': 'https://fiador.vercel.app',
    },
    #Orden de los tags en Swagger
    'TAGS': [
        {'name': 'Login', 'description': 'Operaciones de autenticación'},
        {'name': 'User', 'description': 'Operaciones relacionadas con los usuarios'},
        {'name': 'Token', 'description': 'Operaciones relacionadas con los tokens JWT'},
        {'name': 'Producto', 'description': 'Operaciones relacionadas con los productos'},
        {'name': 'Cliente', 'description': 'Operaciones relacionadas con los clientes'},
        {'name': 'Fiado', 'description': 'Operaciones relacionadas con los fiados'},
    ],
    'SWAGGER_UI_SETTINGS': {
        'persistAuthorization': True,
    }
}


PWA_APP_NAME = 'Fiador API'
PWA_APP_DESCRIPTION = "Fiador API"
PWA_APP_THEME_COLOR = '#0A0302'
PWA_APP_BACKGROUND_COLOR = '#ffffff'
PWA_APP_DISPLAY = 'standalone'
PWA_APP_SCOPE = '/'
PWA_APP_ORIENTATION = 'any'
PWA_APP_START_URL = '/'
PWA_APP_STATUS_BAR_COLOR = 'default'
PWA_APP_ICONS = [
    {'src': '/static/images/icons/icon-72x72.png', 'sizes': '72x72'},
    {'src': '/static/images/icons/icon-96x96.png', 'sizes': '96x96'},
    {'src': '/static/images/icons/icon-128x128.png', 'sizes': '128x128'},
    {'src': '/static/images/icons/icon-144x144.png', 'sizes': '144x144'},
    {'src': '/static/images/icons/icon-152x152.png', 'sizes': '152x152'},
    {'src': '/static/images/icons/icon-192x192.png', 'sizes': '192x192'},
    {'src': '/static/images/icons/icon-384x384.png', 'sizes': '384x384'},
    {'src': '/static/images/icons/icon-512x512.png', 'sizes': '512x512'},
]
PWA_APP_DIR = 'ltr'
PWA_APP_LANG = 'es'